name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Verify code format
        shell: pwsh
        continue-on-error: true
        run: |
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          dotnet format --verify-no-changes

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build test/GestorContrasenas.Tests/GestorContrasenas.Tests.csproj
